DATA_ZIP_PATH: ../Data.zip

INPUT_FILES_PATH:
  Charges: Data/Charges_use.csv
  Damages: Data/Damages_use.csv
  Endorse: Data/Endorse_use.csv
  Primary_Person: Data/Primary_Person_use.csv
  Units: Data/Units_use.csv
  Restrict: Data/Restrict_use.csv

RESULT_PATH: 
  Analysis1: Result/crashMaleCount_analysis1
  Analysis2: Result/twoWheelersCrashCount_analysis2
  Analysis3: Result/top5makersWithDeathAndAirbagFailure_analysis3
  Analysis4: Result/vehiclesCountWithValidLicenceAndHitAndRun_analysis4
  Analysis5: Result/statesWithHighestNoFemaleCrashCount_analysis5
  Analysis6: Result/top3to5CompaniesContributingInjuries_analysis6
  Analysis7: Result/topEthGrpPerBodystyle_analysis7
  Analysis8: Result/top5zipWithMostAlchCarCrashes_analysis8
  Analysis9: Result/uniqueCrashIdsWithNoPropDmgAndInsuranceAvailed_analysis9
  Analysis10: Result/top5brandsWithSpeedCharges_analysis10


